# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-05 13:21
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='blog_img')),
                ('content', ckeditor.fields.RichTextField()),
            ],
        ),
        migrations.CreateModel(
            name='Blog_Categorie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=50)),
                ('catgory_image', models.ImageField(upload_to='blog_cat_image')),
            ],
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('launch_date', models.DateField()),
                ('client', models.CharField(max_length=250)),
                ('live_demo', models.URLField(help_text='Url Field')),
                ('skills', models.CharField(max_length=250)),
                ('project_desc', ckeditor.fields.RichTextField()),
                ('portfolio_image1', models.ImageField(upload_to='portfolio_img')),
                ('portfolio_image2', models.ImageField(blank=True, null=True, upload_to='portfolio_img')),
                ('portfolio_image3', models.ImageField(blank=True, null=True, upload_to='portfolio_img')),
            ],
        ),
        migrations.CreateModel(
            name='Portfolio_Categorie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('port_category', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Studying',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studying_what', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Technologies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('technology', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('testimony', models.TextField()),
                ('job_rank', models.CharField(max_length=300)),
            ],
        ),
        migrations.AddField(
            model_name='portfolio',
            name='port_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='update_site.Portfolio_Categorie'),
        ),
        migrations.AddField(
            model_name='blog',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='update_site.Blog_Categorie'),
        ),
    ]
