# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-07 15:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('update_site', '0002_blog_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonial',
            name='image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='testimony'),
            preserve_default=False,
        ),
    ]
