# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-21 11:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('update_site', '0006_auto_20170921_1240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='title',
            field=models.CharField(max_length=250, unique='UTF8'),
        ),
    ]
