# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-28 15:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('update_site', '0008_auto_20170921_1255'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio',
            name='client',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='launch_date',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='portfolio_image2',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='portfolio_image3',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='project_desc',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='skills',
        ),
    ]
